#+TITLE: About
#+PATH: about
#+MENU: main
#+DATE: 2023-02-27
#+AUTHOR: Tomás Farías Santana
#+WEIGHT: 2
#+DESCRIPTION: Learn more about me.

I'm *Tomás*, a Software Engineer that is looking to document some of my thoughts and, hopefully, help other people in the process. Knowing why I believe a blog should exist may give you an idea of the type of content you may find here; with that being said, I believe a blog exists to:

+ Fill gaps in official documentation by providing practical examples.
+ Raise awareness about a particular issue, topic, or tool.
+ Serve as a source of inspiration by showcasing projects.

In the process of achieving these objectives, I will ramble about programming languages, like Python and Rust, the ecosystem surrounding those languages, Emacs, open-source tools and software, Linux, Software Engineering practices, and probably many others.

If you wish to get in contact with me, you may do so via my projects at [[https://github.com/tomasfarias][GitHub]], through a message via [[https://www.linkedin.com/in/tomasfarias/][LinkedIn]], or by writing me an [[mailto:tomas@tomasfarias.dev][email]].

Thanks for checking out my blog!
